# **COMPUTER VISION**

**UNIVERSIDAD MILITAR NUEVA GRANADA**

**COMPUTER VISION - REGRESIÓN LINEAL**

Ingeniería en Telecomunicaciones.

# 1. Librerías

# 2. Training data (Dataset)

Generar datos de forma similar a anterior ejemplo


# 3. Lectura del dataset por lotes

Aleatorizar y leer por minilotes 

In [ ]:
# Iteraciones para lectura del dataset en formato TensorFlow
def load_array(data_arrays, batch_size, is_train=True):
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

In [ ]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [ ]:
# Prueba de la lectura por minilotes
next(iter(data_iter))

(<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
 array([[ 1.8038919 ,  3.7871861 , -4.9714875 , -3.087479  ],
        [-1.1018147 ,  0.07111602, -0.14876048, -4.895405  ],
        [ 1.6732113 , -5.5855412 ,  9.22918   , -2.2111487 ],
        [ 4.1143084 ,  3.7202218 , -0.58095115, -6.1582403 ],
        [-3.23701   ,  8.221753  , -7.0394807 , -2.4081628 ],
        [-0.6015755 ,  0.6788992 ,  2.3354042 ,  3.6707745 ],
        [ 2.646008  , -4.9522147 ,  3.4264069 ,  0.4978746 ],
        [-0.8199655 , -1.0466094 , -1.780925  ,  4.0639806 ],
        [-0.5789657 ,  4.1715593 , -8.781452  ,  0.30725715],
        [ 1.3753073 ,  2.7680945 ,  5.433372  , -3.558499  ]],
       dtype=float32)>, <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[-1.097033 ],
        [ 2.734994 ],
        [ 5.740307 ],
        [ 3.3647661],
        [-3.854729 ],
        [-3.1846867],
        [ 1.2364385],
        [-4.8349895],
        [-5.6439066],
        [ 3.6140893]], dtype=float32)>)

# 4. Algoritmo de inicialización de parámetros

https://www.tensorflow.org/api_docs/python/tf/keras/initializers


Clase: RandonNormal (especificar argumento desviación estándar)

In [ ]:
initializer = 

# 5. Modelo

*   `tensorflow`: https://www.tensorflow.org/
*   `keras`: https://keras.io/
*   `Sequential` (clase): https://www.tensorflow.org/api_docs/python/tf/keras/Sequential
*   `Dense`: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense

In [ ]:
# Modelo de regresión lineal mediante un modelo secuencial de keras y una capa 
# FC de una neurona

model = 
model.add

# 6. Función de pérdida

https://www.tensorflow.org/api_docs/python/tf/keras/losses

Clase: MeanSquaredError (Error cuadrático medio o norma $L_2$). Utilizar sin argumentos

In [ ]:
# Pérdida por error cuadrático medio
loss = 

# 7. Algoritmo de optimización

Minibatch stochastic gradient descent (SGD)

Argumento: tasa de aprendizaje (learning rate: 0.03)

https://www.tensorflow.org/api_docs/python/tf/keras/optimizers

In [ ]:
trainer = 

# 8. Entrenamiento

En cada época, se realiza una una pasada completa por el conjunto de datos, tomando iterativamente minilotes (entradas y etiquetas).

In [ ]:
num_epochs = 10
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(model(X, training=True), y)
        grads = tape.gradient(l, model.trainable_variables)
        trainer.apply_gradients(zip(grads, model.trainable_variables))
    l = loss(model(features), labels)
    print(f'época {epoch + 1}, pérdida {l:f}')

época 1, pérdida 0.000266
época 2, pérdida 0.000175
época 3, pérdida 0.000159
época 4, pérdida 0.000118
época 5, pérdida 0.000284
época 6, pérdida 0.000106
época 7, pérdida 0.000165
época 8, pérdida 0.000202
época 9, pérdida 0.000137
época 10, pérdida 0.000115


In [ ]:
b

array([-1.0001955], dtype=float32)

Comparación con los parámetros originales

In [ ]:
w = model.get_weights()[0]
print('error al estimar w', w_gen - tf.reshape(w, w_gen.shape))
b = model.get_weights()[1]
print('error al estimar b', b_gen - b)

error al estimar w tf.Tensor([-5.6836754e-04  7.5966120e-05  3.1903386e-04 -2.6744604e-04], shape=(4,), dtype=float32)
error al estimar b [0.0001955]


# 9. Referencias

Dive into Deep Learning